### ISSUE TITLE
1.20.1 forge bug

### ISSUE THREAD

**Issue by peco331** [nimeng1299/AE2CraftingTree#4]
1.20.1forge 在处理复杂合成或某些简单合成（如箱子的合成）时会有查看面板空白的bug，希望可以修复

**Comment by nimeng1299** [comment]
可以提供下存档或者整合包吗，我在gt leisure整合包测试中，合成复杂物品/超时空装配线/没有问题

**Comment by peco331** [comment]
atm9sky整合包

**Comment by nimeng1299** [comment]
能发下存档或简单说下物品的合成步骤吗，例如箱子->橡木木板->橡木原木

**Comment by peco331** [comment]
存档：https://wwl.lanzouv.com/i2v5i2g8o40f  箱子就是橡木原木->橡木木板->箱子，比较复杂的像mek的各种终极工厂，都是从像铁锭红石粉这种基础原料开始合成的。AE相关扩展自己加了AEAdditions和AEInfinityBooster这两个mod

**Comment by nimeng1299** [comment]
感谢提供资料，出现这个问题是因为写样板的时候勾选了`启用替换`(样板编码终端里面的中间3个小按钮的中间那个)，这个问题预计会在下个版本修复

**Comment by peco331** [comment]
好的，感谢您的耐心答复！
